input {
  stdin {
    codec => "json"
  }
}

filter {
  mutate {
    rename => {
      "timestamp" => "log_timestamp"
      "level"     => "log_level"
      "message"   => "log_message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "ridge-training-logs"
  }
  stdout {
    codec => rubydebug {
      metadata => false
    }
  }
}